name: unittests
on: [push, pull_request]

jobs:
  linux-unittests:
    name: Dub Tests
    strategy:
      matrix:
        os: [ubuntu-latest]
        dc: [ldc-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: Install htslib deps
        run: |
            sudo apt-get install -y build-essential autoconf zlib1g-dev libbz2-dev liblzma-dev libcurl4-openssl-dev libssl-dev

      - name: Build htslib
        run: |
            cd htslib
            autoreconf -i
            ./configure
            make
            sudo make install
            sudo ldconfig

      - name: Get htslib commit
        id: get-htslib-commit
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Cache htslib
        uses: actions/cache@v2
        with:
          path: htslib
          key: ${{ runner.os}}-htslib-${{ steps.get-htslib-commit.outputs.sha_short }}

      - name: Run tests
        run: dub -q test -b=unittest-cov
        env:
          LIBRARY_PATH: /usr/local/lib

      - name: Upload coverage
        run: bash <(curl -s https://codecov.io/bash)
